### PR TITLE
If exists, use cfg from git root

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by cofyc** [comment]
what if git does not exist?

**Comment by ghost** [comment]
When the user is not in the git repository, `git rev-parse --show-toplevel` returns `fatal: not a git repository (or any of the parent directories): .git` and `filereadable(l:gitcfg)` fails as it is not a file.

When git is not installed on (my) system, `git rev-parse --show-toplevel` returns `bash: /usr/bin/git: No such file or directory` and `filereadable(l:gitcfg)` fails as it is not a file.

**Comment by ghost** [comment]
It looks like the `system` function does not fail when the return code of the call to the system program fails (i.e., on my system, program returns > 0).

**Comment by cofyc** [comment]
> When the user is not in the git repository, `git rev-parse --show-toplevel` returns `fatal: not a git repository (or any of the parent directories): .git` and `filereadable(l:gitcfg)` fails as it is not a file.
> 
> When git is not installed on (my) system, `git rev-parse --show-toplevel` returns `bash: /usr/bin/git: No such file or directory` and `filereadable(l:gitcfg)` fails as it is not a file.

does this error propagate to VIM console? if it will, it's better to silence these

**Comment by ghost** [comment]
> does this error propagate to VIM console?

Error propagation is exactly the same for `l:gitcfg` as for `l:homecfg` or `l:cwdcfg`, i.e. when `.uncrustify.cfg` is missing in git root, the error propagation is the same as if `.uncrustify.cfg` is missing in the local working directory.

Please, test this patch before merging.

**Pull request merged**
